[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']

remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
  'forge-std/=lib/forge-std/src/'
]

[fuzz]
max_test_rejects = 256
