/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IFixedIncomeNote {
  export type NoteStatusStruct = {
    funded: boolean;
    settled: boolean;
    amount: BigNumberish;
  };

  export type NoteStatusStructOutput = [
    funded: boolean,
    settled: boolean,
    amount: bigint
  ] & { funded: boolean; settled: boolean; amount: bigint };
}

export interface IFixedIncomeNoteInterface extends Interface {
  getFunction(nameOrSignature: "noteStatus"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "SubscriptionSettled"
      | "CouponPaid"
      | "RedemptionPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "noteStatus",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "noteStatus", data: BytesLike): Result;
}

export namespace SubscriptionSettledEvent {
  export type InputTuple = [
    orderId: BytesLike,
    investor: AddressLike,
    amount: BigNumberish,
    currency: string,
    settlementRef: string,
    settlementNetwork: string
  ];
  export type OutputTuple = [
    orderId: string,
    investor: string,
    amount: bigint,
    currency: string,
    settlementRef: string,
    settlementNetwork: string
  ];
  export interface OutputObject {
    orderId: string;
    investor: string;
    amount: bigint;
    currency: string;
    settlementRef: string;
    settlementNetwork: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CouponPaidEvent {
  export type InputTuple = [
    periodId: BigNumberish,
    grossAmount: BigNumberish,
    withholding: BigNumberish,
    netAmount: BigNumberish,
    settlementRef: string,
    settlementNetwork: string
  ];
  export type OutputTuple = [
    periodId: bigint,
    grossAmount: bigint,
    withholding: bigint,
    netAmount: bigint,
    settlementRef: string,
    settlementNetwork: string
  ];
  export interface OutputObject {
    periodId: bigint;
    grossAmount: bigint;
    withholding: bigint;
    netAmount: bigint;
    settlementRef: string;
    settlementNetwork: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionPaidEvent {
  export type InputTuple = [
    amount: BigNumberish,
    settlementRef: string,
    settlementNetwork: string
  ];
  export type OutputTuple = [
    amount: bigint,
    settlementRef: string,
    settlementNetwork: string
  ];
  export interface OutputObject {
    amount: bigint;
    settlementRef: string;
    settlementNetwork: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IFixedIncomeNote extends BaseContract {
  connect(runner?: ContractRunner | null): IFixedIncomeNote;
  waitForDeployment(): Promise<this>;

  interface: IFixedIncomeNoteInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  noteStatus: TypedContractMethod<
    [orderId: BytesLike],
    [IFixedIncomeNote.NoteStatusStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "noteStatus"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [IFixedIncomeNote.NoteStatusStructOutput],
    "view"
  >;

  getEvent(
    key: "SubscriptionSettled"
  ): TypedContractEvent<
    SubscriptionSettledEvent.InputTuple,
    SubscriptionSettledEvent.OutputTuple,
    SubscriptionSettledEvent.OutputObject
  >;
  getEvent(
    key: "CouponPaid"
  ): TypedContractEvent<
    CouponPaidEvent.InputTuple,
    CouponPaidEvent.OutputTuple,
    CouponPaidEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionPaid"
  ): TypedContractEvent<
    RedemptionPaidEvent.InputTuple,
    RedemptionPaidEvent.OutputTuple,
    RedemptionPaidEvent.OutputObject
  >;

  filters: {
    "SubscriptionSettled(bytes32,address,uint256,string,string,string)": TypedContractEvent<
      SubscriptionSettledEvent.InputTuple,
      SubscriptionSettledEvent.OutputTuple,
      SubscriptionSettledEvent.OutputObject
    >;
    SubscriptionSettled: TypedContractEvent<
      SubscriptionSettledEvent.InputTuple,
      SubscriptionSettledEvent.OutputTuple,
      SubscriptionSettledEvent.OutputObject
    >;

    "CouponPaid(uint256,uint256,uint256,uint256,string,string)": TypedContractEvent<
      CouponPaidEvent.InputTuple,
      CouponPaidEvent.OutputTuple,
      CouponPaidEvent.OutputObject
    >;
    CouponPaid: TypedContractEvent<
      CouponPaidEvent.InputTuple,
      CouponPaidEvent.OutputTuple,
      CouponPaidEvent.OutputObject
    >;

    "RedemptionPaid(uint256,string,string)": TypedContractEvent<
      RedemptionPaidEvent.InputTuple,
      RedemptionPaidEvent.OutputTuple,
      RedemptionPaidEvent.OutputObject
    >;
    RedemptionPaid: TypedContractEvent<
      RedemptionPaidEvent.InputTuple,
      RedemptionPaidEvent.OutputTuple,
      RedemptionPaidEvent.OutputObject
    >;
  };
}
