/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFixedIncomeNote } from "./IFixedIncomeNote";
export * as factories from "./factories";
export { IFixedIncomeNote__factory } from "./factories/IFixedIncomeNote__factory";
